name: mobile_application_development_course_project
description: A Flutter application for managing movies.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter_lints paketini devre dışı bırakma
# flutter_lints paketi, kodlama pratiklerini teşvik etmek için kullanılır
# Ancak, projenin ilk aşamalarında, bu kurallar bazen engelleyici olabilir
# Bu nedenle, başlangıçta bu paketi devre dışı bırakabilirsiniz
#  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
